name: Python Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows

    steps:
    - name: Nova-Financial-Solutions-Week-01
      uses: actions/Nova-Financial-Solutions-Week-01

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m venv novenv
        novenv\Scripts\activate
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        novenv\Scripts\activate
        pytest
